# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils


DESCRIPTION="secure, decentralized, fault-tolerant filesystem"
HOMEPAGE="http://allmydata.org/"
SRC_URI="http://pypi.python.org/packages/source/a/allmydata-tahoe/${P}.tar.gz"
LICENSE="GPL-2"
KEYWORDS="~x86"
SLOT="0"
IUSE=""

