# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils subversion


DESCRIPTION="Python library for working with CouchDB"
HOMEPAGE="http://code.google.com/p/couchdb-python/"
ESVN_REPO_URI="http://couchdb-python.googlecode.com/svn/trunk/"
LICENSE="BSD-2"
KEYWORDS="~x86"
SLOT="0"
IUSE=""

DEPEND="dev-python/simplejson
        dev-python/httplib2"
