# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

MY_PN="CouchDB"
MY_P="${MY_PN}-${PV}"
P=${MY_P}

DESCRIPTION="Python library for working with CouchDB"
HOMEPAGE="http://code.google.com/p/couchdb-python/"
SRC_URI="http://pypi.python.org/packages/source/C/CouchDB/${MY_P}.tar.gz"
LICENSE="BSD-2"
KEYWORDS="~x86"
SLOT="0"
IUSE=""

DEPEND="dev-python/simplejson
        dev-python/httplib2"
